import { OpenApiAxios } from "@web-bee-ru/openapi-axios";
import Axios from "axios";
import { getEnv } from "../../../utils/getEnv";
import type { paths as Paths } from "./types"; // generated by openapi-typescript

const axios = Axios.create({
	baseURL: getEnv("CHATBOT_SERVICE_ENDPOINT"),
	adapter: "fetch",
	headers: {
		"Content-Type": "application/json",
		Authorization: `${getEnv("CHATBOT_SERVICE_TOKEN")}`,
	},
});

const api = new OpenApiAxios<Paths, "fetch">(axios, {
	validStatus: "fetch",
});

export const chatbotClient = api;
