/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Health check for coolify */
		get: operations["getHealth"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/chatbot/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["postApiChatbot"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: never;
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	postApiChatbot: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json":
					| {
							/**
							 * Mensagem de texto
							 * @description Mensagem de texto
							 * @example Olá, como vai?
							 * @example Como você está?
							 */
							message: string;
							/**
							 * Lista de URLs de imagens
							 * @description Lista de URLs de imagens
							 * @example [
							 *       "https://example.com/image.png",
							 *       "https://example.com/image.jpg"
							 *     ]
							 */
							images?: string[];
					  }
					| {
							/**
							 * URL do áudio
							 * @description URL do áudio
							 * @example https://example.com/audio.mp3
							 * @example https://example.com/audio.wav
							 */
							audio?: string;
					  };
				"multipart/form-data":
					| {
							/**
							 * Mensagem de texto
							 * @description Mensagem de texto
							 * @example Olá, como vai?
							 * @example Como você está?
							 */
							message: string;
							/**
							 * Lista de URLs de imagens
							 * @description Lista de URLs de imagens
							 * @example [
							 *       "https://example.com/image.png",
							 *       "https://example.com/image.jpg"
							 *     ]
							 */
							images?: string[];
					  }
					| {
							/**
							 * URL do áudio
							 * @description URL do áudio
							 * @example https://example.com/audio.mp3
							 * @example https://example.com/audio.wav
							 */
							audio?: string;
					  };
				"text/plain":
					| {
							/**
							 * Mensagem de texto
							 * @description Mensagem de texto
							 * @example Olá, como vai?
							 * @example Como você está?
							 */
							message: string;
							/**
							 * Lista de URLs de imagens
							 * @description Lista de URLs de imagens
							 * @example [
							 *       "https://example.com/image.png",
							 *       "https://example.com/image.jpg"
							 *     ]
							 */
							images?: string[];
					  }
					| {
							/**
							 * URL do áudio
							 * @description URL do áudio
							 * @example https://example.com/audio.mp3
							 * @example https://example.com/audio.wav
							 */
							audio?: string;
					  };
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
