/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Coolify Utils
		 * @description Health check for coolify
		 */
		get: operations["getHealth"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/chatbot/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Send a message
		 * @description Send a message to the AI chatbot
		 */
		post: operations["postApiChatbot"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: never;
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/**
			 * @description Health check for coolify
			 * @example OK
			 */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": string;
					"multipart/form-data": string;
					"text/plain": string;
				};
			};
		};
	};
	postApiChatbot: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json":
					| {
							/**
							 * Message
							 * @description The message to be sent to the chatbot
							 * @example Hello, how are you?
							 */
							message: string;
							/**
							 * Images
							 * @description The images to be sent to the chatbot
							 * @example [
							 *       "https://example.com/image.png"
							 *     ]
							 */
							images?: string[];
					  }
					| {
							/**
							 * Audio
							 * @description The audio to be sent to the chatbot
							 * @example https://example.com/audio.mp3
							 */
							audio: string;
					  };
				"multipart/form-data":
					| {
							/**
							 * Message
							 * @description The message to be sent to the chatbot
							 * @example Hello, how are you?
							 */
							message: string;
							/**
							 * Images
							 * @description The images to be sent to the chatbot
							 * @example [
							 *       "https://example.com/image.png"
							 *     ]
							 */
							images?: string[];
					  }
					| {
							/**
							 * Audio
							 * @description The audio to be sent to the chatbot
							 * @example https://example.com/audio.mp3
							 */
							audio: string;
					  };
				"text/plain":
					| {
							/**
							 * Message
							 * @description The message to be sent to the chatbot
							 * @example Hello, how are you?
							 */
							message: string;
							/**
							 * Images
							 * @description The images to be sent to the chatbot
							 * @example [
							 *       "https://example.com/image.png"
							 *     ]
							 */
							images?: string[];
					  }
					| {
							/**
							 * Audio
							 * @description The audio to be sent to the chatbot
							 * @example https://example.com/audio.mp3
							 */
							audio: string;
					  };
			};
		};
		responses: {
			/**
			 * No content
			 * @description No content
			 * @example null
			 */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
